version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus


  geo-service:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile.grpc
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - RPC_PROTOCOL=json-rpc
